language: rust
rust:
  - nightly
env:
  - LLVM_VERSION=3.4
  - LLVM_VERSION=3.5
before_install:
  - yes | sudo add-apt-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-${LLVM_VERSION} main"
  - yes | sudo add-apt-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main"
  - sudo apt-get update
install:
  - sudo apt-get install --force-yes libclang-${LLVM_VERSION}-dev llvm-${LLVM_VERSION}-dev
script:
  - export LIBCLANG_PATH=/usr/lib/llvm-${LLVM_VERSION}/lib
  - cargo build --verbose
