[package]
name = "bindgen"
version = "0.16.0"
description = "A binding generator for Rust"
authors = ["Jyun-Yan You <jyyou.tw@gmail.com>"]
license = "BSD-3-Clause"
homepage = "https://github.com/crabtw/rust-bindgen"
repository = "https://github.com/crabtw/rust-bindgen"
readme = "README.md"
keywords = [ "bindings", "ffi", "code-generation" ]

[dependencies]
clang-sys = "~0.6.0"
clippy = { version = "0.0.69", optional = true }
log = "~0.3.6"
libc = "~0.2.11"
syntex_syntax = "~0.32.0"

[features]
static = ["clang-sys/static"]

[[bin]]
name = "bindgen"
doc = false

[[test]]
name = "tests"
