[package]
authors = ["Jyun-Yan You <jyyou.tw@gmail.com>"]
build = "build.rs"
description = "A binding generator for Rust"
homepage = "https://github.com/crabtw/rust-bindgen"
keywords = ["bindings", "ffi", "code-generation"]
license = "BSD-3-Clause"
name = "bindgen"
readme = "README.md"
repository = "https://github.com/crabtw/rust-bindgen"
version = "0.16.0"

[[bin]]
doc = false
name = "bindgen"

[build-dependencies]
quasi_codegen = "0.15"

[dependencies]
clang-sys = "0.8.0"
docopt = "0.6.82"
libc = "0.2.*"
log = "0.3.*"
rustc-serialize = "0.3.19"
syntex_syntax = "0.38"

[dependencies.aster]
features = ["with-syntex"]
version = "0.21.1"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.quasi]
features = ["with-syntex"]
version = "0.15"

[features]
llvm_stable = []
static = []

[lib]
name = "bindgen"
path = "src/lib.rs"

[[test]]
name = "tests"
