[package]

name = "rust-bindgen"
version = "0.13.0"
authors = ["Jyun-Yan You <jyyou.tw@gmail.com>"]
license = "BSD-3-Clause"

build = "build.rs"

[dependencies.log]
git = "https://github.com/rust-lang/log.git"

[features]
static = []

[lib]

name = "bindgen"
path = "src/lib.rs"
plugin = true

[[bin]]

name = "bindgen"
doc = false

[[test]]
name = "tests"
